import { createSlice } from "@reduxjs/toolkit";

const slice = createSlice({
  name: "musicPlayer",
  initialState: [
    {
      id: 1,
      index: 1,
      avatar: "aiChungTinhDuocMai",
      audioName: "Ai Chung Tinh Duoc Mai",
      author: "Dinh Dung",
      duration: "00:05:48",
      iconHeartColor: "#f75253",
    },
    {
      id: 2,
      index: 2,
      avatar: "anhKhongThaThu",
      audioName: "Anh Khong Tha Thu",
      author: "Dinh Dung",
      duration: "00:04:34",
      iconHeartColor: "#f75253",
    },
    {
      id: 3,
      index: 3,
      avatar: "anhThuongEmConNonDai",
      audioName: "Anh Thuong Em Con Non Dai",
      author: "Dinh Dung",
      duration: "00:04:54",
      iconHeartColor: "#f75253",
    },
    {
      id: 4,
      index: 4,
      avatar: "banDuyen",
      audioName: "Ban Duyen",
      author: "Dinh Dung",
      duration: "00:04:25",
      iconHeartColor: "#f75253",
    },
    {
      id: 5,
      index: 5,
      avatar: "cauHenCauThe",
      audioName: "Cau Hen Cau The",
      author: "Dinh Dung",
      duration: "00:05:20",
      iconHeartColor: "#f75253",
    },
    {
      id: 6,
      index: 6,
      avatar: "damCuoiNha",
      audioName: "Dam Cuoi Nha",
      author: "Hong Thanh & DjMie",
      duration: "00:02:54",
      iconHeartColor: "#f75253",
    },
    {
      id: 7,
      index: 7,
      avatar: "deVuong",
      audioName: "De Vuong",
      author: "Dinh Dung",
      duration: "00:04:22",
      iconHeartColor: "#f75253",
    },
    {
      id: 8,
      index: 8,
      avatar: "tungThuong",
      audioName: "Tung Thuong",
      author: "Duy Anh",
      duration: "00:04:10",
      iconHeartColor: "#f75253",
    },
  ],
  reducers: {},
});
export default slice;
